import UrlDisplay from "@/Components/UrlDisplay";

export default async function Home() {

    return (

        <main className="flex w-screen h-auto flex-col">
            <div className="w-full h-auto py-8 border border-slate-300 bg-decor/60">
                <div className="container mx-auto">
                    <div className="flex my-2 max-w-96 flex-col h-auto">
                        <h2 className="py-3 text-primary">
                            Short.url
                        </h2>
                        <h1 className="text-title text-3xl font-semibold">
                            Most Clicked URLS by Shortlink in the last year
                        </h1>
                    </div>
                </div>

                <section className="container mx-auto w-screen my-4">
                    <div className="px-8 py-4 border rounded-lg shadow-md shadow-black/20">

                        <div>
                            <h2 className="text-green-800 font-semibold text-lg my-2">
                                Generated by Short
                            </h2>
                        </div>

                        <div className="">
                            <UrlDisplay />
                        </div>
                    </div>

                    {/*                 <p>
                    Based on data from the Short.url Analytics tool, this page reveals the top 100 most visited Shortlinks within our server, as well as uncovering the top players across various industries.
                </p>

                <p>
                    We are updating this page in a daily basis, so you can stay up to speed with all the market shifts and spot changes in user interest.
                </p> */}

                </section>
            </div >


        </main>



    );
}